### ISSUE TITLE
Landing Pages 

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#10]
On each landing page for each Main Category - is there a space at the Top of the Page - where we can input new language as the seasons change...
i.e. - on New Arrivals - we may want to say something about Summer, and then change that for the Holidays (just like a sentence or two)?

**Comment by corbinsan** [comment]
Yes - this there is an example of this here: http://uat.kirbyandcompany.com/product-category/accents/

"The Accents description will go here and can be changed seasonally!"
