### ISSUE TITLE
new pictures are not showing up?

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#104]
I've made a lot of edits with pictures.  deleting, and adding new ones completely, however the old pictures are still showing up on UAT.  Please advise

**Comment by corbinsan** [comment]
@andreakirbyandcompany Did you save the products in Vend? - you have to save them in Vend to trigger the sync. If so, they should come up as drafts in WP, then you just republish them and they should show up. I tested this process last week, so it does work. I don't see any drafts in UAT.

**Comment by andreakirbyandcompany** [comment]
Yes- I saved them in vend first.
They were not syncing.
I left my paperwork at the office but I will let you know which ones they are tomorrow.

Thanks

Andrea



On Jun 6, 2016, at 3:45 PM, corbinsan <notifications@github.com<mailto:notifications@github.com>> wrote:


@andreakirbyandcompany<https://github.com/andreakirbyandcompany> Did you save the products in Vend? - you have to save them in Vend to trigger the sync. If so, they should come up as drafts in WP, then you just republish them and they should show up. I tested this process last week, so it does work. I don't see any drafts in UAT.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/corbinsan/kirby-and-company/issues/104#issuecomment-224066570>, or mute the thread<https://github.com/notifications/unsubscribe/ARGmsP1DtvH_xsbZ3R4lmHQ0sMOJsCaNks5qJHjbgaJpZM4IvGLE>.

[https://i.imgsafe.org/073a87a31f.png]

Andrea Halvorsen

KIRBY AND COMPANY

1029 Post Road Darien, CT 06820

andrea@kirbyandcompany.com

T:203.309.5900 F:203.309.5899

kirbyandcompany.com
[https://i.imgsafe.org/073e26e3a8.png] [https://i.imgsafe.org/073d14048b.png]  [https://i.imgsafe.org/073e2ddfc1.png]  [https://i.imgsafe.org/073e505339.png]

**Comment by corbinsan** [comment]
@andreakirbyandcompany sounds good, let's connect in the morning after 10 (PST) for me. thanks!

**Comment by andreakirbyandcompany** [comment]
Great. How about 1:30 EST.

THANKS CORBIN!!

Andrea



On Jun 6, 2016, at 5:42 PM, corbinsan <notifications@github.com<mailto:notifications@github.com>> wrote:


@andreakirbyandcompany<https://github.com/andreakirbyandcompany> sounds good, let's connect in the morning after 10 (PST) for me. thanks!

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/corbinsan/kirby-and-company/issues/104#issuecomment-224097603>, or mute the thread<https://github.com/notifications/unsubscribe/ARGmsHLqwS5xD9PCGN8dVJxJ9M0-wvE6ks5qJJRZgaJpZM4IvGLE>.

[https://i.imgsafe.org/073a87a31f.png]

Andrea Halvorsen

KIRBY AND COMPANY

1029 Post Road Darien, CT 06820

andrea@kirbyandcompany.com

T:203.309.5900 F:203.309.5899

kirbyandcompany.com
[https://i.imgsafe.org/073e26e3a8.png] [https://i.imgsafe.org/073d14048b.png]  [https://i.imgsafe.org/073e2ddfc1.png]  [https://i.imgsafe.org/073e505339.png]

**Comment by corbinsan** [comment]
as discussed in #107  - closing
