### ISSUE TITLE
PICTURE ISSUE

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#107]
so this is one I also just noticed...changed the picture weeks ago, and the one that's chosen as the main image is not the main image on UAT
Mason Barware Set with Recipe Book  $98.00

**Comment by andreakirbyandcompany** [comment]
ACTUALLY THIS PRODUCT IS IN VEND, TAGGED CORRECTLY , HAS PICTURES, AND IS NOW NOT SHOWING UP AT ALL ON THE WEBSITE
PLEASE HELP

**Comment by corbinsan** [comment]
@andreakirbyandcompany we have verified sync is working. If you have any issues, remove all product images in Vend, and add the main image first, followed by additional images then save the product. This should re establish a sync for those product images.
