### ISSUE TITLE
jewelry issue

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#108]
not sure what happened with the synch...(but the whole first page, plus the first 7 items on page 2) of  should not be on UAT Jewelry (they are not tagged Jewelry & Fashion / Jewelry, and they don't have a product type)
If you show me how to edit this in WP I can ...I tried..but didn't want to screw up too many things.

thanks

**Comment by corbinsan** [comment]
@andreakirbyandcompany its because I chose the solo "jewelry" category to sync with. I just de selected it.
