### ISSUE TITLE
Sort By

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#11]
We would also like the option to have a drop down on the top of each landing page as well for a 
'Sort By:' option
Price - low to high
Price - high to low
Best Sellers
Newest - Oldest
Oldest - Newest

**Comment by corbinsan** [comment]
Dropdown has been enabled. This is standard with Woo Commerce. We can create custom ones later. Here's what's in UAT (after I push):

Default Sorting (custom + name)
Popularity (sales)
Average rating
Most recent
Sort by price (ascending)
Sort by price (descending)
