### ISSUE TITLE
photo issue again

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#113]
Corbin - remember you updated the necklaces?  Now the old photos are back again!  And they are not even in Vend anymore for each item.  Not sure what's happening...but somewhere something is not syncing correctly....I'm afraid of a lot of changes that I've made,,,that are not making it to UAT

**Comment by corbinsan** [comment]
@andreakirbyandcompany  this is not happening for me: http://uat.kirbyandcompany.com/shop/gift-guide/wile-free-pineapple-necklace/ (the necklace is correct from when I updated the main image)

I really need to know what changes you are making... so we can track any issues per product / update. Thanks
