### ISSUE TITLE
update on UAT

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#13]
Can you please let us know when there is an update with the 'real' categories
Thank you

**Comment by corbinsan** [comment]
@andreakirbyandcompany I ran the sync today and categories are coming in correctly. I only synced about 1000 products out of 3000 but that's because I ended it early.

**Comment by andreakirbyandcompany** [comment]
When you look on the computer version of the UAT - is there a way for you to clean up all the categories.  All the cats/subs are showing on the home page.  Can you fix that, so it's only when you hover over shop that you can see all of those.

**Comment by andreakirbyandcompany** [comment]
Also - there are only about 100-150 products to synch to website....only the Categories that I sent over (all of the products that are tagged 'general' Product Type are not going to the web).  please adivse

**Comment by corbinsan** [comment]
Can you try clearing your cache in the browser for the desktop version in UAT

**Comment by corbinsan** [comment]
I still need to clean out the old products from the full sync that are still in UAT so you may still see some genteral ones until that happens
