### ISSUE TITLE
Instagram Link to product

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#14]
Can we create a Link in the bio of instagram -
that once we post a product, and the consumer clicks on it, it will bring them directly to that item on the website?  We need to utilize Instagram as much as possible...so any direct link to the website would be great. Thanks

**Comment by corbinsan** [comment]
Yes you can. I would recommend a tracking service like bit ly. And only posting one link at a time so when you are posting about a product you can say "to purchase, click link in bio" which could stay up for a day or 2

**Comment by corbinsan** [comment]
I think we can close this issue too
