### ISSUE TITLE
Refund / return policy

### ISSUE THREAD

**Issue by corbinsan** [corbinsan/kirby-and-company#18]
@andreakirbyandcompany Any idea on what this is ?

**Comment by andreakirbyandcompany** [comment]
Hi. Yes- we spoke with cayan today and once we are set up with authorize.net<http://authorize.net> we need to have a return policy in place before the site goes live. So we will need to include this. I am working on the verbiage now....will send it at as a word attachment.

Andrea



On Apr 7, 2016, at 4:26 PM, corbinsan <notifications@github.com<mailto:notifications@github.com>> wrote:


@andreakirbyandcompany<https://github.com/andreakirbyandcompany> Any idea on what this is ?

-
