### ISSUE TITLE
Item inventory

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#2]
Hi Corbin - When you select an item (click through), it currently shows how many units are available.  Can you make that disappear?  We would prefer that the consumer not see how much inventory we have.
Thank you

**Comment by corbinsan** [comment]
@andreakirbyandcompany yes confirming correct use of issues.

**Comment by corbinsan** [comment]
Solved. There is a setting in woocommerce which you can disable stock count. It will still show if item is "instock" however.
