### ISSUE TITLE
0 inventory 

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#22]
How can we on the back end tag items in wordpress/vend to show up with 0 inventory as BACKORDERED.  
Along the talk of last night with items with 0 not showing up at all...I would like any items that are tagged for the website, that have 0 inventory, to show as BACKORDERED.

please advise

**Comment by corbinsan** [comment]
@andreakirbyandcompany  Will advise

**Comment by corbinsan** [comment]
We have the option of showing it as an available product with - inventory, or showing it available while notifying the customer that it's "available on backorder"  - both of these options still make the product on site and available for purchase.
