### ISSUE TITLE
800 #

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#27]
Please update contact info on website with our phone number

855-553-5900
203-309-5900

**Comment by corbinsan** [comment]
@andreakirbyandcompany with both of these phone numbers?

**Comment by andreakirbyandcompany** [comment]
Let's do just the 855 number for now.  Thanks

**Comment by corbinsan** [comment]
done: http://uat.kirbyandcompany.com/contact/
