### ISSUE TITLE
CAT's/ Subs..Please review

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#28]
Sorry - when I ok'd the hover over Shop...I didn't realize all the categories were not in order / correct (I was just so happy they were in 4 sections!), can you please review picture below or I can send you the spreadsheet again with all the Main & subs.
Thanks

<img width="1280" alt="screen shot 2016-04-21 at 11 16 12 am" src="https://cloud.githubusercontent.com/assets/17934000/14714307/835bb394-07b2-11e6-915c-e51b3bd25d16.png">

**Comment by andreakirbyandcompany** [comment]
Can we please get this on the priority list...I need to see how many items are pulling into each cat / sub cat.
Thank you

**Comment by corbinsan** [comment]
@andreakirbyandcompany  In correct order on UAT now.
