### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#3]
We briefly discussed categories.  We are in the process of inputting the new ones into the 'Product type'.  Please confirm: we would like to be able to see all of the main and sub categories when you hover on 'shop' on the main page, and then again on the drop down menu on the 'shop' page.  

If something has a sub category - should that also be entered into 'product type' - or ONLY the main category?  Thank you

**Comment by corbinsan** [comment]
@andreakirbyandcompany  no, sub categories should be put in tags in the following format using 
"category / subcategory":

parent / child / grandchild

**Comment by andreakirbyandcompany** [comment]
Ok, but to make it interesting ;)  If there are 2 main categories (Accents, and Gift Guide will be two of our main cats) that it can go in to...do both of those first?  Then the subs 
i.e.  
Accents / Gift Guide / For Her / For Them

**Comment by corbinsan** [comment]
@andreakirbyandcompany yes for now assign it to one parent category. Then on the woocommerce side we can add the product to the other main category.

**Comment by corbinsan** [comment]
Closing, just ran a sync and mapping is correct.
