### ISSUE TITLE
Need to add new Category 

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#30]
Can we please add 'As Seen In' as a new category.  Pictured below where it should go
<img width="1280" alt="screen shot 2016-04-21 at 11 28 20 am" src="https://cloud.githubusercontent.com/assets/17934000/14714761/36a51692-07b4-11e6-98ec-7585774fbd59.png">

**Comment by andreakirbyandcompany** [comment]
Add it as discussed in it's own column

**Comment by corbinsan** [comment]
@andreakirbyandcompany  on UAT - closing
