### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#36]
Featured items gets replaced with 'Currently Coveting'

The 4 main pictures below that will click thru to the following categories (Elephant, Blue & White, Barware, Jewelry)  Pictures to follow.  No text on the pictures at all.  We should be able to edit these photos as necessary (for future walk thru on wordpress)

Below that:
Best Sellers gets replaced with 'Our Favorites'

**Comment by corbinsan** [comment]
@andreakirbyandcompany  These edits are complete, I just need the images you would like to use for those categories ( I know you are working on them as a whole, but for this section they should be different). Yes, they are editable in wordpress, no problem we can review that.
