### ISSUE TITLE
Shopping Bag

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#53]
I emailed you a picture of our shopping bag, and how elaine would now like the font to look on it if possible.

**Comment by corbinsan** [comment]
@andreakirbyandcompany  Best I can do is place the "K & Co" Image on it. 
![shopping-bag-2](https://cloud.githubusercontent.com/assets/1753312/15025205/0ae7b742-11ed-11e6-9380-1d7086fd96c7.png)
