### ISSUE TITLE
build shop drop down menu

### ISSUE THREAD

**Issue by corbinsan** [corbinsan/kirby-and-company#6]

**Comment by corbinsan** [comment]
I'm playing with redesigning this so it's not as long.

**Comment by corbinsan** [comment]
@andreakirbyandcompany horizontal menu on UAT: http://uat.kirbyandcompany.com/

**Comment by andreakirbyandcompany** [comment]
looks awesome!!  Thanks

**Comment by corbinsan** [comment]
cool, I'm just going to make some padding adjustments then I'll close this.
