### ISSUE TITLE
build contact form submission (is this going to Vend or constant contact) ?

### ISSUE THREAD

**Issue by corbinsan** [corbinsan/kirby-and-company#8]
@andreakirbyandcompany please let me know where the form will submit data to.

**Comment by andreakirbyandcompany** [comment]
We did discuss this - we would like it to go to Vend please

**Comment by corbinsan** [comment]
I setup an application with Vend, and am using their API to submit the data to Vend as a new customer. There is an issue I'm having with the API access token, which expires every 24 hours. Need to write a script that generates a new key every time.

**Comment by corbinsan** [comment]
@andreakirbyandcompany what do you use for email marketing? constant contact?

**Comment by andreakirbyandcompany** [comment]
Yes -
we use constant contact


Andrea Halvorsen
Online / Purchasing Manager
KIRBY AND COMPANY
1029 Post Road Darien, CT 06820
a<mailto:elaine@kirbyandcompany.com>ndrea@kirbyandcompany.com<mailto:ndrea@kirbyandcompany.com>
T:203.309.5900 F:203.309.5899
kirbyandcompany.com<http://kirbyandcompany.com>

[cid:B417BEBA-1D80-46BA-A69A-23484D744867]<http://instagram.com/kirby_and_company>   <http://instagram.com/kirby_and_company> [cid:E65EAF42-167A-4F0A-8060-5D53E7E70A70] <https://www.facebook.com/pages/Kirby-and-Company/284224375072961>    <https://www.facebook.com/pages/Kirby-and-Company/284224375072961> [cid:38B8C345-4A44-406F-B373-6CB16AE90332] <http://www.pinterest.com/kirbyandcompany/>    <http://www.pinterest.com/kirbyandcompany/> [cid:552AE9CA-E646-4E08-9A01-DC26198978D3]     <https://twitter.com/KirbyandCoCT>
<https://twitter.com/KirbyandCoCT>

On Apr 20, 2016, at 1:41 PM, corbinsan <notifications@github.com<mailto:notifications@github.com>> wrote:


@andreakirbyandcompany<https://github.com/andreakirbyandcompany> what do you use for email marketing? constant contact?

**Comment by corbinsan** [comment]
@andreakirbyandcompany I was able to submit the contact form to Vend as a new customer. There will also be an email that is sent with the information and the message.
