### ISSUE TITLE
Add Design Therapy to Main Nav Page

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#82]
This can be the last one (all the way to the right)

Design Therapy

Once clicked on...'Coming Soon'

Add Contact info: Design@kirbyandcompany.com

This is where we will be posting to/from the blog, (can people sign up through this page for the blog...it would be a separate sign up then the pop-up on the main page)

**Comment by corbinsan** [comment]
@andreakirbyandcompany lets dicuss this UX a bit more. You only post to the blog, people will not sign up for it. They sign up in the contact page.

**Comment by corbinsan** [comment]
@andreakirbyandcompany design therapy page is added. What else do you want on that page for now?
