### ISSUE TITLE
Sizing of item outline

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#85]
So , we need to figure out how to configure each rectangle to be the same size...I know you said it had something to do with the picture.  but, this is a must do as we're getting closer to launch...need to see them all the same size

**Comment by corbinsan** [comment]
@andreakirbyandcompany  yes, it's all related to the main product image. This needs to be square to fit the design.

**Comment by corbinsan** [comment]
@andreakirbyandcompany sounds like this is in progress with your designer in house so I'm closing here.
