### ISSUE TITLE
Lets discuss item pictures

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#86]
Ok - so most of the pictures look great when they are little...then once you click on the item to see it, or to add to cart, it gets all stretched out and distorted....can we just keep the same size image for when you click on an item so it doesn't do that....and then maybe add a hovering 'zoom' feature??

**Comment by corbinsan** [comment]
@andreakirbyandcompany  no this will not work on desktop views. The image will be too small. Its necessary to use higher res images (square) for the products.
