### ISSUE TITLE
Ceramic Elephant Wall Art  $94.00 not showing up at all in any of tagged categories.  please advise

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#89]

**Comment by corbinsan** [comment]
@andreakirbyandcompany when a proudct like this one syncs with 0 inventory it comes in hidden, Just chagned it to visible. http://uat.kirbyandcompany.com/product-category/wall-decor/ I don't have a fix for that yet, but I did bulk edit so its a quick process.
