### ISSUE TITLE
remove item

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#92]
Cuff Bracelet- Hammered Gold  $19.00 needs to be removed...do I need to start putting things in the 'removefromweb' tag - or should I still just be able to delete tags / categories to remove it?
thanks

**Comment by corbinsan** [comment]
@andreakirbyandcompany no you have to remove all tags from the product, then tag with "removeFromWeb" - capital letters count.

**Comment by corbinsan** [comment]
@andreakirbyandcompany hidden for now
