### ISSUE TITLE
Web Text

### ISSUE THREAD

**Issue by andreakirbyandcompany** [corbinsan/kirby-and-company#98]
Hi Corbin -

Last week we sent over revised text for the entire web...can you let me know where we stand on that being updated?

**Comment by corbinsan** [comment]
Some of this copy needs to be designed back into the pages since it was removed fro the original design.   I just can't add it back in randomly, but I will try to update the parts that already exist. In progress.

**Comment by corbinsan** [comment]
@andreakirbyandcompany all of the copy is updated in UAT
